### ISSUE TITLE
Generated API docs have duplicate IDs for '<section>' and '<table>' elements

### ISSUE THREAD

**Issue by tseaver** [googleapis/googleapis#31] opened 2016-05-13 15:15 UTC
The [Subscriber section link](https://cloud.google.com/pubsub/reference/rpc/google.pubsub.v1#google.pubsub.v1.Subscriber) works, but the [link for `CreateSubscriber`](https://cloud.google.com/pubsub/reference/rpc/google.pubsub.v1#google.pubsub.v1.Subscriber.CreateSubscriber`) does not, because the ID is duplicated for both the `<section>` and the `<table>`.

**Comment by geigerj** [comment] 2016-06-22 00:06
@ethanbao 

Thanks for reporting this. The tool that generates the language-independent API is not open-source, so I will make sure that this is being tracked internally.

**Comment by geigerj** [comment] 2016-06-22 00:11
Actually, I'm not sure exactly what the issue is. There is no `CreateSubscriber` method, which is why that link doesn't work. The link for `CreateSubscription` seems to work fine: [https://cloud.google.com/pubsub/reference/rpc/google.pubsub.v1#google.pubsub.v1.Subscriber.google.pubsub.v1.Subscriber.CreateSubscription](https://cloud.google.com/pubsub/reference/rpc/google.pubsub.v1#google.pubsub.v1.Subscriber.google.pubsub.v1.Subscriber.CreateSubscription)

**Comment by tseaver** [comment] 2016-06-22 02:27
The `CreateSubscription` ID is still duplicated, which is a) invalid HTML, and b) can confuse the browser when using it as an anchor:

```html
        <section id="google.pubsub.v1.Subscriber.google.pubsub.v1.Subscriber.CreateSubscription">
          <table class="matchpre" id="google.pubsub.v1.Subscriber.google.pubsub.v1.Subscriber.CreateSubscription">
```

**Comment by geigerj** [comment] 2016-06-22 17:47
Got it. Tracking this internally as a bug.

**Comment by geigerj** [comment] 2016-09-27 17:02
I'm closing this, since it's tracked elsewhere.

**Closed by geigerj** 2016-09-27 17:02 UTC
